name: Collect Tweets

on:
  schedule:
    - cron: "0 * * * *"   # runs every hour
  workflow_dispatch:       # allow manual trigger

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate requirements.txt
        run: |
          echo "pandas" > requirements.txt
          echo "snscrape" >> requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run collector
        run: python collector.py

      - name: Commit & push data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv requirements.txt
          git commit -m "Update tweets on $(date)" || echo "No new files to commit"
          git push
